version: '3.8'

services:
  mysql-container:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: db_jwtsecure
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    networks:
      - app-network

  eureka-server:
    build:
      context: ./DirectoryService
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - app-network

  auth-service:
    build:
      context: ./jwtAuthService
    container_name: authentication-service
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mysql-container          # corrigé ici
      - eureka-server # corrigé ici
    networks:
      - app-network

  gateway-service:
    build:
      context: ./cloudGateway
    container_name: gateway-service
    ports:
      - "8088:8088"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server # corrigé ici
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
