server:
  port: 8088

spring:
  application:
    name: gateway-service
  jwt:
    privateKey: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "http://localhost:3000"
            allowCredentials: true
            allowedHeaders:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
