# === Profiles ===
spring.profiles.active=local

# === Application ===
spring.application.name=auth-service
server.port=${SERVER_PORT:8080}

# === JPA ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# === Discovery ===
spring.cloud.discovery.enabled=true

# === File Upload ===
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
file.upload-dir=uploads

# === Cloudinary ===
cloudinary.enabled=${CLOUDINARY_ENABLED:false}
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:ddajnk5q8}
cloudinary.api-key=${CLOUDINARY_API_KEY:118248927783633}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:3-RlCv0RTNUZlIE3I-i_S_ltSIQ}

# === Google Maps ===
google.maps.api.key=fake_google_maps_api_key_for_example

# === JWT ===
spring.jwt.securityKey=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
spring.jwt.privateKey=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
spring.jwt.expiration=360000